[providers]
php = true
node = true

[phases.setup]
nixPkgs = ['php82', 'nodejs_20', 'npm']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[phases.deploy]
cmds = ['php artisan optimize:clear', 'php artisan migrate --force', 'php artisan serve --host 0.0.0.0 --port $PORT']